--SET REFERENTIAL_INTEGRITY FALSE;

set FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE place;
TRUNCATE TABLE member;
TRUNCATE TABLE player;
TRUNCATE TABLE game_result;
TRUNCATE TABLE game;
TRUNCATE TABLE hint;

--SET REFERENTIAL_INTEGRITY TRUE;
--
--TRUNCATE TABLE member;
--TRUNCATE TABLE player;

set FOREIGN_KEY_CHECKS = 1;
