SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE place_statistics;
TRUNCATE TABLE place_like;
TRUNCATE TABLE place;
TRUNCATE TABLE member;
TRUNCATE TABLE player;
TRUNCATE TABLE game_result;
TRUNCATE TABLE game;
TRUNCATE TABLE hint;
TRUNCATE TABLE auth_token;

SET REFERENTIAL_INTEGRITY TRUE;
