spring:
  # for test
  h2:
    console:
      enabled: true
  datasource:
    # for test
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop # for test
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true # for test
    show-sql: true # for test

multipartFile:
  directory:
    path: ./src/test/resources/image
