name: NAAGA ANDROID CI

on:
  pull_request:
    branches: [ dev_android ]
    paths:
      - 'android/**'

jobs:
  ktlint:
    name: ktlint check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/android/.gradle/caches
            ~/android/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Local Properties
        env:
          API_KEY: ${{ secrets.BASE_URL }}
          KAKAO_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
          KAKAO_SCHEME: ${{ secrets.KAKAO_REDIRECTION_SCHEME }}
        run: |
          echo BASE_URL=\"$API_KEY\" >> ./local.properties
          echo KAKAO_NATIVE_APP_KEY=\"KAKAO_APP_KEY\" >> ./local.properties
          echo kakao_redirection_scheme=\"KAKAO_SCHEME\" >> ./local.properties

      - name: Run ktlint
        run: ./gradlew ktlintCheck

  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/android/.gradle/caches
            ~/android/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Local Properties
        env:
          API_KEY: ${{ secrets.BASE_URL }}
          KAKAO_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
          KAKAO_SCHEME: ${{ secrets.KAKAO_REDIRECTION_SCHEME }}
        run: |
          echo BASE_URL=\"$API_KEY\" >> ./local.properties
          echo KAKAO_NATIVE_APP_KEY=\"KAKAO_APP_KEY\" >> ./local.properties
          echo kakao_redirection_scheme=\"KAKAO_SCHEME\" >> ./local.properties

      - name: Add Google Service Json file
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON_FILE }}' > ./app/google-services.json

      - name: Run Build
        run: ./gradlew assembleDebug

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/android/.gradle/caches
            ~/android/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add Local Properties
        env:
          API_KEY: ${{ secrets.BASE_URL }}
          KAKAO_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
          KAKAO_SCHEME: ${{ secrets.KAKAO_REDIRECTION_SCHEME }}
        run: |
          echo BASE_URL=\"$API_KEY\" >> ./local.properties
          echo KAKAO_NATIVE_APP_KEY=\"KAKAO_APP_KEY\" >> ./local.properties
          echo kakao_redirection_scheme=\"KAKAO_SCHEME\" >> ./local.properties

      - name: Add Google Service Json file
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON_FILE }}' > ./app/google-services.json

      - name: Run Build
        run: ./gradlew testDebugUnitTest
