name: NAAGA BACKEND MERGE CI

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  execute_deployment_script:
    name: backend deploy
    runs-on: naaga

    steps:
      - name: Execute script
        run: |
          sudo ./deploy.sh
        working-directory: /home/ubuntu

