name: NAAGA BACKEND MERGE CI

on:
  push:
    branches: 
      - dev
    paths:
      - backend/**
      
jobs:
  deploy:
    name: backend deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout GitHub
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:latest

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:latest
