name: NAAGA BACKEND PULL REQUEST CI

on:
  push:
    branches:
      - feat/#214

jobs:
  build_test:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x backend/gradlew

      - name: Prepare config files
        working-directory: backend
        run: |
          # Copy appropriate config for tests
          cp src/main/resources/security/application-test.yml src/main/resources/application.yml

      - name: Build and Test
        working-directory: backend
        run: ./gradlew --no-daemon build test

      - name: Run application with application-local.yml
        working-directory: backend
        run: |
          # Copy appropriate config for running application
          cp src/main/resources/security/application-local.yml src/main/resources/application.yml

          # Run the application
          ./gradlew --no-daemon bootRun --args='--spring.config.location=src/main/resources/application.yml'
