name: NAAGA BACKEND PULL REQUEST CI

on:
  pull_request:
    branches: 
      - dev
      
jobs:
  build_test:
    name: backend check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true  # 모든 서브모듈도 체크아웃
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: 삭제한다
      run: |
        rm src/main/resources/application.yml

    - name: 복사한다
      run: |
        cp src/main/resources/security/application-local.yml src/main/resources/application.yml

    - name: Build with Gradle
      run: ./gradlew build

    - name: 삭제한다
      run: |
        rm src/main/resources/application.yml

    - name: 복사한다
      run: |
        cp src/main/resources/security/application-test.yml src/main/resources/application.yml
        
    - name: Test with Gradle
      run: ./gradlew test
