name: NAAGA BACKEND PULL REQUEST CI

on:
  pull_request:
    branches: 
      - dev_backend
    paths:
      - backend/**
      
jobs:
  build_test:
    name: backend check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true  # 모든 서브모듈도 체크아웃
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: 삭제한다
      run: |
        rm src/main/resources/application.yml

    - name: 복사한다
      run: |
        cp src/main/resources/security/application-local.yml src/main/resources/application.yml

    - name: Build with Gradle
      run: ./gradlew build

    - name: 삭제한다
      run: |
        rm src/main/resources/application.yml

    - name: 복사한다
      run: |
        cp src/main/resources/security/application-test.yml src/main/resources/application.yml
        
    - name: Test with Gradle
      run: ./gradlew test

    - name: 테스트 결과를 PR에 코멘트로 등록합니다
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: 'backend/build/test-results/test/TEST-*.xml'

    - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록합니다
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        token: ${{ github.token }}
