name: NAAGA PROJECT CI

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: merge release -> dev_backend
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: dev_backend
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: merge release -> dev_android
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: dev_android
        github_token: ${{ secrets.GITHUB_TOKEN }}
    